#!/bin/bash

_usage() {
  cat <<EOF
usage: git do-all [OPTION] <message>

Options:

-M|--major - Update for major release
-m|--minor - Update for a minor release
-B|--bugfix - Update for a bug fix (default)
-b|--build - Update for a build
-p|--push - Push all unpushed changes

EOF
}

branch="$(git show-branch --current | sed 's/\[\(.*\)\].*/\1/')"
if [ -z "${branch}" ]; then
  echo "Unable to detect the current branch"
  exit 1
fi

# if ( echo "${location}" | grep -qs 'tags/' ); then
#   echo "You are not on a branch. Please checkout a branch before proceeding"
#   exit
# fi

if [ $# -lt 1 ]; then
  _usage
  exit 1
fi

definc="-B"
if [ $# -eq 2 ]; then
  definc="${1}"
  shift
fi

force_push=0
tag="$(git describe --tags | cut -d'-' -f1)"
major="$(echo "${tag}" | cut -d'.' -f1)"
minor="$(echo "${tag}" | cut -d'.' -f2)"
bugfix="$(echo "${tag}" | cut -d'.' -f3)"
build="$(echo "${tag}" | cut -d'.' -f4)"

case $definc in
  -M|--major)
    major=$(( $major + 1 ))
    minor=0
    bugfix=0
    build='a'
  ;;
  
  -m|--minor)
    minor=$(( $minor + 1 ))
    bugfix=0
    build='a'
  ;;
  
  -B|--bugfix)
    bugfix=$(( $bugfix + 1 ))
    build='a'
  ;;
  
  -b|--build)
    case "${build}" in
      a) build='b'; ;;
      b) build=0; ;;
      *)
        build=$(( $build + 1 ))
      ;;
    esac
  ;;
  
  -p|--push)
    force_push=1
  ;;
esac

if [ $force_push -eq 0 -a -z "$(git status --porcelain)" ]; then
  echo "There's nothing to commit. Use -p if you intend to just push"
  exit 1
fi

tag="${major}.${minor}.${bugfix}.${build}"

set -e

if [ $force_push -eq 1 ]; then
  git push --atomic origin "${branch}" "${tag}"
  exit 0
fi

git add -A
git commit -m "${@}"
git tag "${tag}"
git checkout "${branch}"
git push --atomic origin "${branch}" "${tag}"