#!/bin/bash

DEBUG="${DEBUG:-}"
TMPDIR="$(mktemp -d)"
CONFIG="${TMPDIR}/config"
SCRIPT_SED="${TMPDIR}/getscript.sed"
VARS_SED="${TMPDIR}/getvars.sed"
nfe=0
elno=0
errlinlim=2

# filterpipe <pipepath> <sed_output> <outpipe>
filterpipe() (
  (
    if [ ! -p "${1}" ]; then mkfifo "${1}"; fi
    sed "s/\(.*\)/${2}/" < "${1}" >&$3
  ) &
  while [ ! -p "${1}" ]; do sleep 0.1; done
  kill %1
)

@e() { elno=$1; shift; errmsg="${@}"; }

onerror() {
  if [ $nfe -ne 1 ]; then
    if [ $(( $LINENO - $elno )) -le $errlinlim ]; then
      echo -e "\033[0;31m! ${errmsg}\033[0m" >&4 
    fi
    exit 10; 
  fi
}

filterpipe "${TMPDIR}/out" '| \1' 1
filterpipe "${TMPDIR}/err" "$(printf '\033')[0;31m! \1$(printf '\033')[0m" 2

shopt -s extdebug
exec 3>&1 4>&2 5>&1
exec 1>"${TMPDIR}/out" 2>"${TMPDIR}/err"

test ! -z $DEBUG && trap 'echo -e "\033[1;34m? ${BASH_COMMAND}\033[0m" >&5' DEBUG
trap 'rm -rf "${TMPDIR}"' EXIT
trap onerror ERR

### FACTOR CODE ###
GIT_ROOT="$(git rev-parse --show-toplevel)"
FACTDIR="${GIT_ROOT}/.factor"

_usage() {
  cat <<'EOF' >&5
%doc%
EOF
}

# _get_vars <resource>
_get_vars() {
  cat <<'EOF' | sed "s@%1%@${1}@;s@%GR%@${GIT_ROOT}@" >"${VARS_SED}"
/\[%1%\]/,/^\s*\[[a-zA-Z0-9_-]*\]/!d
//d
/^\s*$/d
s/^\s*\([a-zA-Z][a-zA-Z0-9]*=.*\)/\1/
s@%git%@%GR%@
p
EOF
  sed -n -f "${VARS_SED}" < "${CONFIG}"
}

# _get_vars <resource>
_get_script() {
  cat <<'EOF' | sed "s@%1%@${1}@;s@%GR%@${GIT_ROOT}@" >"${SCRIPT_SED}"
/\[%1%\]/,/^\s*\[[a-zA-Z0-9_-]*\]/!d
//d
#/^\s*$/d
p
EOF
  sed -n -f "${SCRIPT_SED}" < "${CONFIG}"
}

_compose_config() {
  find "${GIT_ROOT}" -type f -name *.ftr | \
  while read file; do
    cat "${file}"
    echo -ne "\n\n"
  done > "${CONFIG}"
  cat <<EOF >>"${CONFIG}"
[default_factor_values]
  tag=master
  prefix=%git%

[endoffactorconfig]
EOF
}

# _compose_entry <entry>
_compose_entry() {
  _get_vars "${1}" | \
  sed 's/\(.*\)/f_\1/' | \
  sed "s/=\"/='/;s/\"\s*\$/'/" | \
  sed "s/=/='/;s/\$/'/"
}

# _compose_script scr1 ... scrN
_compose_script() {
  for scr in $f_script; do
    _get_script "${scr}"
  done > "${f_script_file}"
  chmod +x "${f_script_file}"
}

# _compose_environment env1 ... envN
_compose_environment() {
  (
  cat <<EOF
PREFIX_CACHE="${f_cache}"
PREFIX_BUILD="${f_prefix}"
GIT_ROOT="${GIT_ROOT}"
EOF
  for envi in $f_env; do
    _get_vars "${envi}"
  done | sed 's/=\(.*\)/="\1"/; /^\s*#/d'
  ) | sed 's/\(.*\)/export \1/'
}

# _get_resource <resource>
_get_resource() {
  source <(_compose_entry "default_factor_values")
  source <(_compose_entry "factor")
  source <(_compose_entry "${1}")
  
  @e $LINENO "No url defined for ${1}"
  test ! -z "${f_url}"
  @e $LINENO "No prefix provided for ${1}"
  test ! -z "${f_prefix}"
  @e $LINENO "No script sections specified for ${1}"
  test ! -z "${f_script}"
  
  f_moddir="${FACTDIR}/${1}"
  f_lock="${f_moddir}/lock"
  f_cache="${f_moddir}/cache"
  f_module="${f_moddir}/module"
  f_tagfile="${f_moddir}/tag"
  f_rmodule="${RFACTDIR}/${1}/module"
  f_script_file="${TMPDIR}/${1}.sh"
}

# _build <resource>
_build() {
  if [ ! -d "${f_moddir}" ]; then mkdir -p "${f_moddir}"; fi
  if [ ! -f "${f_lock}" ]; then touch "${f_lock}"; fi
  if [ ! -f "${f_tag}" ]; then touch "${f_tagfile}"; fi
  
  _compose_script
  
  @e $LINENO "Could not pull the module ${1}"
  if [ ! -d "${f_module}" ]; then
    git clone "${f_url}" -b "${f_tag}" "${f_module}" 2>&1 >/dev/null
  fi

  curr_hash="$(md5sum "${f_script_file}" | head -c32)"
  lock_hash="$(cat "${f_lock}")"
  lock_tag="$(cat "${f_tagfile}")"
  
  deprebuilt=0
  while read req; do
    if [ -z "${req}" ]; then continue; fi
    @e $LINENO "Requirement '${req}' for resource '${1}' failed to build";
    nfe=1
    $0 build "${req}"
    res=$?
    nfe=0
    case $res in
      12) continue; ;;
      11) deprebuilt=1; ;;
      *) exit 1; ;;
    esac
  done < <(echo "${f_requires}" | sed 's/ /\n/g')
  
  if [ $deprebuilt -ne 1 -a -d "${f_cache}" -a \
    "${curr_hash}" == "${lock_hash}" -a "${f_tag}" == "${lock_tag}" ]; then
    mkdir -p "${f_prefix}"
    rsync -a "${f_cache}/" "${f_prefix}/"
    exit 12
  fi
  
  rm -rf "${f_cache}"
  mkdir -p "${f_cache}"
  
  pushd "${f_module}" >/dev/null

  @e $LINENO "Refusing to build; target git directory is the parent not the submodule: '${1}'"
  test "${GIT_ROOT}" != "$(git rev-parse --show-toplevel)"

  (
    git fetch --all
    git checkout "${f_tag}"
    git reset --hard "${f_tag}"
    git clean -xfdf
  ) 2>&1 >/dev/null

  popd >/dev/null

  source <(_compose_environment)
  @e $LINENO "Failed to build package ${1}"
  env -C "${f_module}" "${f_script_file}"

  mkdir -p "${f_prefix}"
  rsync -a "${f_cache}/" "${f_prefix}/"
  echo "${curr_hash}" > "${f_lock}"
  echo "${f_tag}" > "${f_tagfile}"
  exit 11
}

mkdir -p "${FACTDIR}"
if ! grep -qs '^.factor' "${GIT_ROOT}/.gitignore"; then
  echo ".factor" >> "${GIT_ROOT}/.gitignore"
fi

_compose_config

if [ $# -lt 2 ]; then
  _usage
  @e $LINENO "Too few arguments"
  /bin/false
fi

OPER="${1}"
shift

while [ $# -gt 0 ]; do
  _get_resource "${1}"
  case "${OPER}" in
    build) _build "${1}"; exit $?; ;;
    clean) rm -rf "${f_moddir}"; ;;
    *) _usage; exit 1; ;;
  esac
  shift
done
